[package]
name = "Firmware"
version = "0.1.0"
edition = "2024"

[dependencies]
bluer = { version = "0.17.4", features = ["full"] }
lazy_static = "1.5.0"
rppal = "0.22.1"
tokio = {version = "1.48.0", features = ["full"]}
tokio-macros = { version = "0.2.0-alpha.6" }
